### ISSUE TITLE
Not working with Hassos ?

### ISSUE THREAD

**Issue by thundergreen** [definitio/ha-sox#4]
Hello I get this error. It worked in the past until i swapped to HassOS. Don't know if this is related?
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 618, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sox/media_player.py", line 194, in update
    self._send('')  # For compatibility with old sound server
  File "/config/custom_components/sox/media_player.py", line 162, in _send
    output = sock.recv(256).decode('utf-8').rstrip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 102: invalid continuation byte
```

I installed Caletudo package Pre-build from your page link.

The installed sox version is: sox:      SoX v14.4.1

**Comment by definitio** [comment]
I need your help to reproduce a problem. Can you save this script to file (change hostname or IP at line 5), run it and show me an output?

```python
#!/usr/bin/env python3

import socket

HOST = 'vacuum.lan'
PORT = 7777

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
    sock.settimeout(5)
    sock.connect((HOST, PORT))
    sock.sendall(";1.0;".encode())
    output = sock.recv(256)

print(output)
```

**Comment by thundergreen** [comment]
Hello,

thanks for zour response.

here the output:

```
./vacuum.sh 
b'playing=False;volume=1.0'
```

**Comment by definitio** [comment]
The output is correct. Tested HassOS 6.4 - it works without errors.

**Comment by thundergreen** [comment]
Hello.. dunno what went wrong but all of sudden it works now :) Thanks anyway

**Comment by thundergreen** [comment]
Sorry to bother again. Updated Valetudo (Hypher) and tried above command and it returned same value but I get same error message again in Home-assistant:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 618, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sox/media_player.py", line 194, in update
    self._send('')  # For compatibility with old sound server
  File "/config/custom_components/sox/media_player.py", line 162, in _send
    output = sock.recv(256).decode('utf-8').rstrip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 102: invalid continuation byte
```
Running latest HassOS and tested in terminal and it worked with the file but home assistant throws error .

**Comment by thundergreen** [comment]
ok strange.. now it works again :P
